version: '3.3'

services:
  db:
    image: postgis/postgis:15-3.4
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=esa_cms
    volumes:
      - pgdata:/var/lib/postgresql/data
  cms:
    build:
      context: .
      dockerfile: cms/Dockerfile.prod
    ports:
      - '1337:1337'
    env_file:
      - ./cms/.env
    environment:
      - NODE_ENV=${NODE_ENV:-development}
    links:
      - db
    depends_on:
      - db
    volumes:
      - ./cms:/app/cms
      - /app/cms/src/plugins/map-field/node_modules
      - /app/cms/src/plugins/map-field/dist
  client:
    build:
      context: .
      dockerfile: client/Dockerfile.prod
    ports:
      - '3000:3000'
    env_file:
      - ./client/.env.local
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:1337/api
      - NODE_ENV=${NODE_ENV:-development}
    links:
      - cms
    volumes:
      - ./client:/app/client

volumes:
  pgdata:
