import '@/styles/globals.css';
import '@/styles/mapbox.css';

import Providers from '@/app/layout-providers';

import Map from '@/containers/home/map';

import Fonts from '@/components/ui/fonts';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <Providers>
      <html lang="en">
        <Fonts />
        <body className="font-notes h-screen w-screen">
          <main className="flex flex-col">
            <div>
              <Map />
              {children}
            </div>
          </main>
        </body>
      </html>
    </Providers>
  );
}
